name: Daily LeetCode Extractor

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch
      - GitHub-Pages-Branch  # Triggers the workflow on push to the GitHub-Pages-Branch branch
      - GitHub-Page-extractor-performance-venv # Triggers the workflow on push to the GitHub-Page-extractor-performance-venv branch

jobs:
  run-extractor:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Set the timeout to 15 minutes

    steps:
      - name: Checkout repository # Checks-out the repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.2'

        # Runs a command to upgrade pip and install the dependencies listed in requirements.txt.
      - name: Install dependencies 
        run: |
          python3 -m pip install --upgrade pip 
          python3 -m pip install "pymongo[srv]"==3.11
          pip install -r requirements.txt

      - name: Run LeetCode Extractor
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: python3 src/main.py
